// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GuardianAuditRecord struct {
	Sequence   int64              `json:"sequence"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ActorType  string             `json:"actor_type"`
	ActorID    string             `json:"actor_id"`
	Action     string             `json:"action"`
	ObjectType string             `json:"object_type"`
	ObjectID   string             `json:"object_id"`
	Metadata   []byte             `json:"metadata"`
	TraceID    pgtype.Text        `json:"trace_id"`
}

type GuardianJobsJob struct {
	JobID       string             `json:"job_id"`
	JobType     string             `json:"job_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
	LeaseUntil  pgtype.Timestamptz `json:"lease_until"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GuardianSystemServiceState struct {
	StateKey   string             `json:"state_key"`
	StateValue []byte             `json:"state_value"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
