package audit

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

const (
	// DefaultListLimit and MaxListLimit are the approved H5-A read bounds.
	DefaultListLimit int32 = 50
	MaxListLimit     int32 = 200

	// Identity bounds match the storage checks and reject hostile text before
	// it crosses the domain boundary.
	MaxIdentityBytes            = 256
	MaxCorrelationIdentityBytes = 128

	// Audit timestamp bounds and precision match PostgreSQL timestamptz and
	// the public RFC3339 JSON representation.
	MinAuditTimestampYear   = 1
	MaxAuditTimestampYear   = 9999
	AuditTimestampPrecision = time.Microsecond
)

var (
	ErrInvalidEvent     = errors.New("invalid audit event")
	ErrInvalidRecord    = errors.New("invalid audit record")
	ErrInvalidListQuery = errors.New("invalid audit list query")
	ErrInvalidPage      = errors.New("invalid audit page")
	ErrInvalidTimestamp = errors.New("invalid audit timestamp")
)

// Actor identifies the system, authenticated user, or device responsible for
// an event. Actor IDs are required for every actor type, including system.
type Actor struct {
	Type ActorType
	ID   string
}

// ObjectRef identifies the exact resource affected by an audit action.
type ObjectRef struct {
	Type ObjectType
	ID   string
}

// Event is the validated input to an append operation. OccurredAt is supplied
// by the caller; RecordedAt and EventID are generated by PostgreSQL.
type Event struct {
	OccurredAt    time.Time
	Actor         Actor
	Action        Action
	Object        ObjectRef
	CorrelationID string
	RequestID     string
	Before        *Snapshot
	After         *Snapshot
}

// Record is a durable stored event. Sequence is internal pagination state and
// must not be exposed by the public API.
type Record struct {
	EventID    string
	Sequence   int64
	RecordedAt time.Time
	Event      Event
}

// ListQuery describes an exact-filter, newest-first audit read. A zero Cursor
// denotes the first page. A zero Limit is normalized to DefaultListLimit.
type ListQuery struct {
	Limit         int32
	Cursor        Cursor
	Action        Action
	CorrelationID string
	ObjectType    ObjectType
	ObjectID      string
}

// Page contains durable records and an opaque cursor for the next page. An
// empty NextCursor means there is no later page.
type Page struct {
	Records    []Record
	NextCursor string
}

// Appender is implemented by a storage adapter bound to the mutation's
// transaction. Domain packages depend on this interface, never on pgx.
type Appender interface {
	Append(context.Context, Event) (Record, error)
}

// Reader provides authorized, deterministic audit reads.
type Reader interface {
	List(context.Context, ListQuery) (Page, error)
}

// Validate enforces every domain invariant before an event reaches storage.
func (e Event) Validate() error {
	if err := validateAuditTimestamp("occurred_at", e.OccurredAt); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidEvent, err)
	}
	if err := e.Actor.Type.Validate(); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidEvent, err)
	}
	if err := validateRequiredIdentity("actor ID", e.Actor.ID, MaxIdentityBytes); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidEvent, err)
	}
	if err := ValidateActionObject(e.Action, e.Object.Type); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidEvent, err)
	}
	if err := validateRequiredIdentity("object ID", e.Object.ID, MaxIdentityBytes); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidEvent, err)
	}
	if err := validateRequiredIdentity("correlation ID", e.CorrelationID, MaxCorrelationIdentityBytes); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidEvent, err)
	}
	if e.RequestID != "" {
		if err := validateRequiredIdentity("request ID", e.RequestID, MaxCorrelationIdentityBytes); err != nil {
			return fmt.Errorf("%w: %w", ErrInvalidEvent, err)
		}
	}
	if e.Before != nil {
		if err := e.Before.Validate(); err != nil {
			return fmt.Errorf("%w: invalid before snapshot: %w", ErrInvalidEvent, err)
		}
	}
	if e.After != nil {
		if err := e.After.Validate(); err != nil {
			return fmt.Errorf("%w: invalid after snapshot: %w", ErrInvalidEvent, err)
		}
	}
	return nil
}

// Validate enforces durable-record identity and the embedded event contract.
func (r Record) Validate() error {
	if !validUUIDv7(r.EventID) {
		return fmt.Errorf("%w: event ID is not UUIDv7", ErrInvalidRecord)
	}
	if r.Sequence <= 0 {
		return fmt.Errorf("%w: sequence must be positive", ErrInvalidRecord)
	}
	if err := validateAuditTimestamp("recorded_at", r.RecordedAt); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidRecord, err)
	}
	if err := r.Event.Validate(); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidRecord, err)
	}
	return nil
}

// Validate checks bounds, cursor integrity, closed filters, and the paired
// object filter. Limit zero is valid and means DefaultListLimit.
func (q ListQuery) Validate() error {
	if q.Limit < 0 || q.Limit > MaxListLimit {
		return fmt.Errorf("%w: limit must be between 1 and %d or zero for default", ErrInvalidListQuery, MaxListLimit)
	}
	if !q.Cursor.IsZero() {
		if err := q.Cursor.Validate(); err != nil {
			return fmt.Errorf("%w: %w", ErrInvalidListQuery, err)
		}
	}
	if q.Action != "" {
		if err := q.Action.Validate(); err != nil {
			return fmt.Errorf("%w: %w", ErrInvalidListQuery, err)
		}
	}
	if q.CorrelationID != "" {
		if err := validateRequiredIdentity("correlation ID", q.CorrelationID, MaxCorrelationIdentityBytes); err != nil {
			return fmt.Errorf("%w: %w", ErrInvalidListQuery, err)
		}
	}
	hasObjectType := q.ObjectType != ""
	hasObjectID := q.ObjectID != ""
	if hasObjectType != hasObjectID {
		return fmt.Errorf("%w: object type and object ID filters must be supplied together", ErrInvalidListQuery)
	}
	if hasObjectType {
		if err := q.ObjectType.Validate(); err != nil {
			return fmt.Errorf("%w: %w", ErrInvalidListQuery, err)
		}
		if q.Action != "" {
			if err := ValidateActionObject(q.Action, q.ObjectType); err != nil {
				return fmt.Errorf("%w: %w", ErrInvalidListQuery, err)
			}
		}
		if err := validateRequiredIdentity("object ID", q.ObjectID, MaxIdentityBytes); err != nil {
			return fmt.Errorf("%w: %w", ErrInvalidListQuery, err)
		}
	}
	return nil
}

// Normalized validates q and applies the H5-A default page limit.
func (q ListQuery) Normalized() (ListQuery, error) {
	if err := q.Validate(); err != nil {
		return ListQuery{}, err
	}
	if q.Limit == 0 {
		q.Limit = DefaultListLimit
	}
	return q, nil
}

// Validate checks records and verifies that the next cursor is opaque but
// well-formed. It does not expose or derive record sequences.
func (p Page) Validate() error {
	if len(p.Records) > int(MaxListLimit) {
		return fmt.Errorf("%w: page contains %d records; maximum is %d", ErrInvalidPage, len(p.Records), MaxListLimit)
	}
	for i := range p.Records {
		if err := p.Records[i].Validate(); err != nil {
			return fmt.Errorf("%w: record %d: %w", ErrInvalidPage, i, err)
		}
		if i > 0 && p.Records[i-1].Sequence <= p.Records[i].Sequence {
			return fmt.Errorf("%w: records are not in strict newest-first sequence order", ErrInvalidPage)
		}
	}
	if p.NextCursor != "" {
		cursor, err := ParseCursor(p.NextCursor)
		if err != nil {
			return fmt.Errorf("%w: %w", ErrInvalidPage, err)
		}
		if len(p.Records) == 0 {
			return fmt.Errorf("%w: an empty page cannot have a next cursor", ErrInvalidPage)
		}
		if cursor.PositionSequence != p.Records[len(p.Records)-1].Sequence {
			return fmt.Errorf("%w: next cursor position does not match the final record", ErrInvalidPage)
		}
		if p.Records[0].Sequence > cursor.AnchorSequence {
			return fmt.Errorf("%w: page record exceeds the cursor anchor", ErrInvalidPage)
		}
	}
	return nil
}

func validateRequiredIdentity(name, value string, maximum int) error {
	if value == "" || strings.TrimSpace(value) != value {
		return fmt.Errorf("%s is required and must not have surrounding whitespace", name)
	}
	if !utf8.ValidString(value) {
		return fmt.Errorf("%s must be valid UTF-8", name)
	}
	if len(value) > maximum {
		return fmt.Errorf("%s exceeds %d bytes", name, maximum)
	}
	for _, r := range value {
		if unicode.IsControl(r) {
			return fmt.Errorf("%s contains a control character", name)
		}
	}
	return nil
}

func validateAuditTimestamp(name string, value time.Time) error {
	persistedUTC := value.UTC().Truncate(AuditTimestampPrecision)
	if !persistedUTC.After(time.Time{}) || persistedUTC.Year() < MinAuditTimestampYear || persistedUTC.Year() > MaxAuditTimestampYear {
		return fmt.Errorf(
			"%w: %s UTC instant at PostgreSQL microsecond precision must be after the Go zero time and within year %d..%d",
			ErrInvalidTimestamp,
			name,
			MinAuditTimestampYear,
			MaxAuditTimestampYear,
		)
	}
	if _, err := value.MarshalJSON(); err != nil {
		return fmt.Errorf("%w: %s is not RFC3339 JSON serializable: %v", ErrInvalidTimestamp, name, err)
	}
	return nil
}

func validUUIDv7(value string) bool {
	if len(value) != 36 || value[8] != '-' || value[13] != '-' || value[18] != '-' || value[23] != '-' {
		return false
	}
	if value[14] != '7' {
		return false
	}
	switch value[19] {
	case '8', '9', 'a', 'b', 'A', 'B':
	default:
		return false
	}
	for i, c := range []byte(value) {
		if i == 8 || i == 13 || i == 18 || i == 23 {
			continue
		}
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
			return false
		}
	}
	return true
}
