// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAuditAnchorLock = `-- name: AcquireAuditAnchorLock :exec
SELECT pg_advisory_xact_lock(1196769618, 1)
`

// The two-key advisory-lock namespace is (0x47554152 = "GUAR", 1 = audit
// append/anchor protocol v1). The first-page reader takes the exclusive side.
func (q *Queries) AcquireAuditAnchorLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireAuditAnchorLock)
	return err
}

const appendAuditRecord = `-- name: AppendAuditRecord :one
WITH audit_append_lock AS MATERIALIZED (
    -- Appends take the shared form so they remain concurrent. Materialization
    -- and the INSERT's dependency on this row guarantee the lock is acquired
    -- before PostgreSQL evaluates the identity default for the new record.
    SELECT pg_advisory_xact_lock_shared(1196769618, 1)
)
INSERT INTO guardian_audit.records (
    occurred_at,
    actor_type,
    actor_id,
    action,
    object_type,
    object_id,
    correlation_id,
    request_id,
    before_snapshot,
    after_snapshot
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
FROM audit_append_lock
RETURNING
    event_id::text AS event_id,
    sequence,
    occurred_at,
    recorded_at,
    actor_type,
    actor_id,
    action,
    object_type,
    object_id,
    correlation_id,
    request_id,
    before_snapshot,
    after_snapshot
`

type AppendAuditRecordParams struct {
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	ActorType      string             `json:"actor_type"`
	ActorID        string             `json:"actor_id"`
	Action         string             `json:"action"`
	ObjectType     string             `json:"object_type"`
	ObjectID       string             `json:"object_id"`
	CorrelationID  string             `json:"correlation_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	BeforeSnapshot []byte             `json:"before_snapshot"`
	AfterSnapshot  []byte             `json:"after_snapshot"`
}

type AppendAuditRecordRow struct {
	EventID        string             `json:"event_id"`
	Sequence       int64              `json:"sequence"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	ActorType      string             `json:"actor_type"`
	ActorID        string             `json:"actor_id"`
	Action         string             `json:"action"`
	ObjectType     string             `json:"object_type"`
	ObjectID       string             `json:"object_id"`
	CorrelationID  string             `json:"correlation_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	BeforeSnapshot []byte             `json:"before_snapshot"`
	AfterSnapshot  []byte             `json:"after_snapshot"`
}

func (q *Queries) AppendAuditRecord(ctx context.Context, arg AppendAuditRecordParams) (AppendAuditRecordRow, error) {
	row := q.db.QueryRow(ctx, appendAuditRecord,
		arg.OccurredAt,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.CorrelationID,
		arg.RequestID,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
	)
	var i AppendAuditRecordRow
	err := row.Scan(
		&i.EventID,
		&i.Sequence,
		&i.OccurredAt,
		&i.RecordedAt,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.ObjectType,
		&i.ObjectID,
		&i.CorrelationID,
		&i.RequestID,
		&i.BeforeSnapshot,
		&i.AfterSnapshot,
	)
	return i, err
}

const getAuditAnchor = `-- name: GetAuditAnchor :one
SELECT COALESCE(MAX(sequence), 0)::bigint AS anchor_sequence
FROM guardian_audit.records
`

func (q *Queries) GetAuditAnchor(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAuditAnchor)
	var anchor_sequence int64
	err := row.Scan(&anchor_sequence)
	return anchor_sequence, err
}

const listAuditRecords = `-- name: ListAuditRecords :many
SELECT
    event_id::text AS event_id,
    sequence,
    occurred_at,
    recorded_at,
    actor_type,
    actor_id,
    action,
    object_type,
    object_id,
    correlation_id,
    request_id,
    before_snapshot,
    after_snapshot
FROM guardian_audit.records
WHERE sequence <= $1
  AND (
      $2::bigint = 0
      OR sequence < $2
  )
  AND (
      $3::text = ''
      OR action = $3
  )
  AND (
      $4::text = ''
      OR correlation_id = $4
  )
  AND (
      $5::text = ''
      OR (
          object_type = $5
          AND object_id = $6
      )
  )
ORDER BY sequence DESC
LIMIT $7
`

type ListAuditRecordsParams struct {
	AnchorSequence      int64  `json:"anchor_sequence"`
	PositionSequence    int64  `json:"position_sequence"`
	FilterAction        string `json:"filter_action"`
	FilterCorrelationID string `json:"filter_correlation_id"`
	FilterObjectType    string `json:"filter_object_type"`
	FilterObjectID      string `json:"filter_object_id"`
	PageSize            int32  `json:"page_size"`
}

type ListAuditRecordsRow struct {
	EventID        string             `json:"event_id"`
	Sequence       int64              `json:"sequence"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	ActorType      string             `json:"actor_type"`
	ActorID        string             `json:"actor_id"`
	Action         string             `json:"action"`
	ObjectType     string             `json:"object_type"`
	ObjectID       string             `json:"object_id"`
	CorrelationID  string             `json:"correlation_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	BeforeSnapshot []byte             `json:"before_snapshot"`
	AfterSnapshot  []byte             `json:"after_snapshot"`
}

func (q *Queries) ListAuditRecords(ctx context.Context, arg ListAuditRecordsParams) ([]ListAuditRecordsRow, error) {
	rows, err := q.db.Query(ctx, listAuditRecords,
		arg.AnchorSequence,
		arg.PositionSequence,
		arg.FilterAction,
		arg.FilterCorrelationID,
		arg.FilterObjectType,
		arg.FilterObjectID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRecordsRow{}
	for rows.Next() {
		var i ListAuditRecordsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Sequence,
			&i.OccurredAt,
			&i.RecordedAt,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.CorrelationID,
			&i.RequestID,
			&i.BeforeSnapshot,
			&i.AfterSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
