// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthCredentialByUserID = `-- name: GetAuthCredentialByUserID :one
SELECT user_id::text AS user_id,
       username,
       status,
       password_phc,
       totp_seed_envelope,
       last_totp_counter
FROM guardian_auth.users
WHERE user_id = $1
`

type GetAuthCredentialByUserIDRow struct {
	UserID           string `json:"user_id"`
	Username         string `json:"username"`
	Status           string `json:"status"`
	PasswordPhc      string `json:"password_phc"`
	TotpSeedEnvelope []byte `json:"totp_seed_envelope"`
	LastTotpCounter  int64  `json:"last_totp_counter"`
}

func (q *Queries) GetAuthCredentialByUserID(ctx context.Context, userID pgtype.UUID) (GetAuthCredentialByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthCredentialByUserID, userID)
	var i GetAuthCredentialByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Status,
		&i.PasswordPhc,
		&i.TotpSeedEnvelope,
		&i.LastTotpCounter,
	)
	return i, err
}

const getAuthCredentialByUsername = `-- name: GetAuthCredentialByUsername :one
SELECT user_id::text AS user_id,
       username,
       status,
       password_phc,
       totp_seed_envelope,
       last_totp_counter
FROM guardian_auth.users
WHERE username = $1
`

type GetAuthCredentialByUsernameRow struct {
	UserID           string `json:"user_id"`
	Username         string `json:"username"`
	Status           string `json:"status"`
	PasswordPhc      string `json:"password_phc"`
	TotpSeedEnvelope []byte `json:"totp_seed_envelope"`
	LastTotpCounter  int64  `json:"last_totp_counter"`
}

func (q *Queries) GetAuthCredentialByUsername(ctx context.Context, username string) (GetAuthCredentialByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAuthCredentialByUsername, username)
	var i GetAuthCredentialByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Status,
		&i.PasswordPhc,
		&i.TotpSeedEnvelope,
		&i.LastTotpCounter,
	)
	return i, err
}

const listAuthSessions = `-- name: ListAuthSessions :many
SELECT session_id::text AS session_id,
       s.user_id::text AS user_id,
       u.username,
       u.role,
       s.created_at,
       s.last_seen_at,
       s.expires_at,
       s.revoked_at
FROM guardian_auth.sessions s
JOIN guardian_auth.users u ON u.user_id = s.user_id
WHERE s.user_id = $1
ORDER BY s.created_at DESC, s.session_id DESC
LIMIT 200
`

type ListAuthSessionsRow struct {
	SessionID  string             `json:"session_id"`
	UserID     string             `json:"user_id"`
	Username   string             `json:"username"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListAuthSessions(ctx context.Context, userID pgtype.UUID) ([]ListAuthSessionsRow, error) {
	rows, err := q.db.Query(ctx, listAuthSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthSessionsRow{}
	for rows.Next() {
		var i ListAuthSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
