// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpEnvironmentRevision = `-- name: BumpEnvironmentRevision :exec
UPDATE guardian_environment.environments
SET revision = revision + 1,
    updated_at = clock_timestamp()
WHERE environment_id = $1
`

func (q *Queries) BumpEnvironmentRevision(ctx context.Context, environmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpEnvironmentRevision, environmentID)
	return err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO guardian_environment.environments (organization_id, display_name, name_key)
VALUES (
    (SELECT organization_id FROM guardian_environment.organizations WHERE singleton = true),
    $1,
    $2
)
RETURNING environment_id::text AS environment_id,
          organization_id::text AS organization_id,
          display_name,
          revision,
          created_at,
          updated_at
`

type CreateEnvironmentParams struct {
	DisplayName string `json:"display_name"`
	NameKey     string `json:"name_key"`
}

type CreateEnvironmentRow struct {
	EnvironmentID  string             `json:"environment_id"`
	OrganizationID string             `json:"organization_id"`
	DisplayName    string             `json:"display_name"`
	Revision       int64              `json:"revision"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (CreateEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.DisplayName, arg.NameKey)
	var i CreateEnvironmentRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createZone = `-- name: CreateZone :one
INSERT INTO guardian_environment.zones (environment_id, display_name, name_key, network)
VALUES (
    $1,
    $2,
    $3,
    $4::cidr
)
RETURNING zone_id::text AS zone_id,
          environment_id::text AS environment_id,
          display_name,
          network::text AS cidr,
          revision,
          created_at,
          updated_at
`

type CreateZoneParams struct {
	EnvironmentID pgtype.UUID  `json:"environment_id"`
	DisplayName   string       `json:"display_name"`
	NameKey       string       `json:"name_key"`
	Network       netip.Prefix `json:"network"`
}

type CreateZoneRow struct {
	ZoneID        string             `json:"zone_id"`
	EnvironmentID string             `json:"environment_id"`
	DisplayName   string             `json:"display_name"`
	Cidr          string             `json:"cidr"`
	Revision      int64              `json:"revision"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (CreateZoneRow, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.EnvironmentID,
		arg.DisplayName,
		arg.NameKey,
		arg.Network,
	)
	var i CreateZoneRow
	err := row.Scan(
		&i.ZoneID,
		&i.EnvironmentID,
		&i.DisplayName,
		&i.Cidr,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteZone = `-- name: DeleteZone :execrows
DELETE FROM guardian_environment.zones
WHERE environment_id = $1
  AND zone_id = $2
`

type DeleteZoneParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ZoneID        pgtype.UUID `json:"zone_id"`
}

func (q *Queries) DeleteZone(ctx context.Context, arg DeleteZoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteZone, arg.EnvironmentID, arg.ZoneID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT e.environment_id::text AS environment_id,
       e.organization_id::text AS organization_id,
       e.display_name,
       e.revision,
       COUNT(z.zone_id)::bigint AS zone_count,
       CASE WHEN COUNT(z.zone_id) = 0 THEN 'needs_zones' ELSE 'zones_defined' END::text AS status,
       e.created_at,
       e.updated_at
FROM guardian_environment.environments e
LEFT JOIN guardian_environment.zones z ON z.environment_id = e.environment_id
WHERE e.environment_id = $1
  AND e.organization_id = (SELECT organization_id FROM guardian_environment.organizations WHERE singleton = true)
GROUP BY e.environment_id
`

type GetEnvironmentRow struct {
	EnvironmentID  string             `json:"environment_id"`
	OrganizationID string             `json:"organization_id"`
	DisplayName    string             `json:"display_name"`
	Revision       int64              `json:"revision"`
	ZoneCount      int64              `json:"zone_count"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEnvironment(ctx context.Context, environmentID pgtype.UUID) (GetEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getEnvironment, environmentID)
	var i GetEnvironmentRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.Revision,
		&i.ZoneCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentForUpdate = `-- name: GetEnvironmentForUpdate :one
SELECT environment_id::text AS environment_id,
       organization_id::text AS organization_id,
       display_name,
       name_key,
       revision,
       created_at,
       updated_at
FROM guardian_environment.environments
WHERE environment_id = $1
  AND organization_id = (SELECT organization_id FROM guardian_environment.organizations WHERE singleton = true)
FOR UPDATE
`

type GetEnvironmentForUpdateRow struct {
	EnvironmentID  string             `json:"environment_id"`
	OrganizationID string             `json:"organization_id"`
	DisplayName    string             `json:"display_name"`
	NameKey        string             `json:"name_key"`
	Revision       int64              `json:"revision"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEnvironmentForUpdate(ctx context.Context, environmentID pgtype.UUID) (GetEnvironmentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentForUpdate, environmentID)
	var i GetEnvironmentForUpdateRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.NameKey,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationSingleton = `-- name: GetOrganizationSingleton :one
SELECT organization_id::text AS organization_id, created_at
FROM guardian_environment.organizations
WHERE singleton = true
`

type GetOrganizationSingletonRow struct {
	OrganizationID string             `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOrganizationSingleton(ctx context.Context) (GetOrganizationSingletonRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationSingleton)
	var i GetOrganizationSingletonRow
	err := row.Scan(&i.OrganizationID, &i.CreatedAt)
	return i, err
}

const getZone = `-- name: GetZone :one
SELECT z.zone_id::text AS zone_id,
       z.environment_id::text AS environment_id,
       z.display_name,
       z.network::text AS cidr,
       z.revision,
       z.created_at,
       z.updated_at
FROM guardian_environment.zones z
JOIN guardian_environment.environments e ON e.environment_id = z.environment_id
WHERE z.environment_id = $1
  AND z.zone_id = $2
  AND e.organization_id = (SELECT organization_id FROM guardian_environment.organizations WHERE singleton = true)
`

type GetZoneParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ZoneID        pgtype.UUID `json:"zone_id"`
}

type GetZoneRow struct {
	ZoneID        string             `json:"zone_id"`
	EnvironmentID string             `json:"environment_id"`
	DisplayName   string             `json:"display_name"`
	Cidr          string             `json:"cidr"`
	Revision      int64              `json:"revision"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetZone(ctx context.Context, arg GetZoneParams) (GetZoneRow, error) {
	row := q.db.QueryRow(ctx, getZone, arg.EnvironmentID, arg.ZoneID)
	var i GetZoneRow
	err := row.Scan(
		&i.ZoneID,
		&i.EnvironmentID,
		&i.DisplayName,
		&i.Cidr,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getZoneForUpdate = `-- name: GetZoneForUpdate :one
SELECT z.zone_id::text AS zone_id,
       z.environment_id::text AS environment_id,
       z.display_name,
       z.name_key,
       z.network::text AS cidr,
       z.revision,
       z.created_at,
       z.updated_at
FROM guardian_environment.zones z
JOIN guardian_environment.environments e ON e.environment_id = z.environment_id
WHERE z.environment_id = $1
  AND z.zone_id = $2
  AND e.organization_id = (SELECT organization_id FROM guardian_environment.organizations WHERE singleton = true)
FOR UPDATE OF z
`

type GetZoneForUpdateParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ZoneID        pgtype.UUID `json:"zone_id"`
}

type GetZoneForUpdateRow struct {
	ZoneID        string             `json:"zone_id"`
	EnvironmentID string             `json:"environment_id"`
	DisplayName   string             `json:"display_name"`
	NameKey       string             `json:"name_key"`
	Cidr          string             `json:"cidr"`
	Revision      int64              `json:"revision"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetZoneForUpdate(ctx context.Context, arg GetZoneForUpdateParams) (GetZoneForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getZoneForUpdate, arg.EnvironmentID, arg.ZoneID)
	var i GetZoneForUpdateRow
	err := row.Scan(
		&i.ZoneID,
		&i.EnvironmentID,
		&i.DisplayName,
		&i.NameKey,
		&i.Cidr,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT e.environment_id::text AS environment_id,
       e.organization_id::text AS organization_id,
       e.display_name,
       e.revision,
       COUNT(z.zone_id)::bigint AS zone_count,
       CASE WHEN COUNT(z.zone_id) = 0 THEN 'needs_zones' ELSE 'zones_defined' END::text AS status,
       e.created_at,
       e.updated_at
FROM guardian_environment.environments e
LEFT JOIN guardian_environment.zones z ON z.environment_id = e.environment_id
GROUP BY e.environment_id
ORDER BY e.name_key, e.environment_id
LIMIT $1
`

type ListEnvironmentsRow struct {
	EnvironmentID  string             `json:"environment_id"`
	OrganizationID string             `json:"organization_id"`
	DisplayName    string             `json:"display_name"`
	Revision       int64              `json:"revision"`
	ZoneCount      int64              `json:"zone_count"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEnvironments(ctx context.Context, limit int32) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsRow{}
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.OrganizationID,
			&i.DisplayName,
			&i.Revision,
			&i.ZoneCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZones = `-- name: ListZones :many
SELECT z.zone_id::text AS zone_id,
       z.environment_id::text AS environment_id,
       z.display_name,
       z.network::text AS cidr,
       z.revision,
       z.created_at,
       z.updated_at
FROM guardian_environment.zones z
WHERE z.environment_id = $1
  AND z.environment_id IN (
      SELECT e.environment_id
      FROM guardian_environment.environments e
      WHERE e.organization_id = (
          SELECT organization_id FROM guardian_environment.organizations WHERE singleton = true
      )
  )
ORDER BY z.name_key, z.zone_id
LIMIT $2
`

type ListZonesParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	Limit         int32       `json:"limit"`
}

type ListZonesRow struct {
	ZoneID        string             `json:"zone_id"`
	EnvironmentID string             `json:"environment_id"`
	DisplayName   string             `json:"display_name"`
	Cidr          string             `json:"cidr"`
	Revision      int64              `json:"revision"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListZones(ctx context.Context, arg ListZonesParams) ([]ListZonesRow, error) {
	rows, err := q.db.Query(ctx, listZones, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZonesRow{}
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ZoneID,
			&i.EnvironmentID,
			&i.DisplayName,
			&i.Cidr,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnvironmentZoneSet = `-- name: LockEnvironmentZoneSet :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 1464554834))
`

func (q *Queries) LockEnvironmentZoneSet(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, lockEnvironmentZoneSet, environmentID)
	return err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE guardian_environment.environments
SET display_name = $2,
    name_key = $3,
    revision = revision + 1,
    updated_at = clock_timestamp()
WHERE environment_id = $1
RETURNING environment_id::text AS environment_id,
          organization_id::text AS organization_id,
          display_name,
          revision,
          created_at,
          updated_at
`

type UpdateEnvironmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	DisplayName   string      `json:"display_name"`
	NameKey       string      `json:"name_key"`
}

type UpdateEnvironmentRow struct {
	EnvironmentID  string             `json:"environment_id"`
	OrganizationID string             `json:"organization_id"`
	DisplayName    string             `json:"display_name"`
	Revision       int64              `json:"revision"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (UpdateEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, updateEnvironment, arg.EnvironmentID, arg.DisplayName, arg.NameKey)
	var i UpdateEnvironmentRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateZone = `-- name: UpdateZone :one
UPDATE guardian_environment.zones
SET display_name = $1,
    name_key = $2,
    network = $3::cidr,
    revision = revision + 1,
    updated_at = clock_timestamp()
WHERE environment_id = $4
  AND zone_id = $5
RETURNING zone_id::text AS zone_id,
          environment_id::text AS environment_id,
          display_name,
          network::text AS cidr,
          revision,
          created_at,
          updated_at
`

type UpdateZoneParams struct {
	DisplayName   string       `json:"display_name"`
	NameKey       string       `json:"name_key"`
	Network       netip.Prefix `json:"network"`
	EnvironmentID pgtype.UUID  `json:"environment_id"`
	ZoneID        pgtype.UUID  `json:"zone_id"`
}

type UpdateZoneRow struct {
	ZoneID        string             `json:"zone_id"`
	EnvironmentID string             `json:"environment_id"`
	DisplayName   string             `json:"display_name"`
	Cidr          string             `json:"cidr"`
	Revision      int64              `json:"revision"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (UpdateZoneRow, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.DisplayName,
		arg.NameKey,
		arg.Network,
		arg.EnvironmentID,
		arg.ZoneID,
	)
	var i UpdateZoneRow
	err := row.Scan(
		&i.ZoneID,
		&i.EnvironmentID,
		&i.DisplayName,
		&i.Cidr,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const zoneOverlapExists = `-- name: ZoneOverlapExists :one
SELECT EXISTS (
    SELECT 1
    FROM guardian_environment.zones
    WHERE environment_id = $1
      AND network && $2::cidr
      AND ($3::uuid IS NULL OR zone_id <> $3::uuid)
) AS overlaps
`

type ZoneOverlapExistsParams struct {
	EnvironmentID pgtype.UUID  `json:"environment_id"`
	Network       netip.Prefix `json:"network"`
	ExcludeZoneID pgtype.UUID  `json:"exclude_zone_id"`
}

func (q *Queries) ZoneOverlapExists(ctx context.Context, arg ZoneOverlapExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, zoneOverlapExists, arg.EnvironmentID, arg.Network, arg.ExcludeZoneID)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}
