// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foundation.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditRecord = `-- name: AppendAuditRecord :one
INSERT INTO guardian_audit.records (
    actor_type, actor_id, action, object_type, object_id, metadata, trace_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING sequence, occurred_at
`

type AppendAuditRecordParams struct {
	ActorType  string      `json:"actor_type"`
	ActorID    string      `json:"actor_id"`
	Action     string      `json:"action"`
	ObjectType string      `json:"object_type"`
	ObjectID   string      `json:"object_id"`
	Metadata   []byte      `json:"metadata"`
	TraceID    pgtype.Text `json:"trace_id"`
}

type AppendAuditRecordRow struct {
	Sequence   int64              `json:"sequence"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AppendAuditRecord(ctx context.Context, arg AppendAuditRecordParams) (AppendAuditRecordRow, error) {
	row := q.db.QueryRow(ctx, appendAuditRecord,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Metadata,
		arg.TraceID,
	)
	var i AppendAuditRecordRow
	err := row.Scan(&i.Sequence, &i.OccurredAt)
	return i, err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO guardian_jobs.jobs (job_id, job_type, payload, status, available_at)
VALUES ($1, $2, $3, 'queued', $4)
`

type CreateJobParams struct {
	JobID       string             `json:"job_id"`
	JobType     string             `json:"job_type"`
	Payload     []byte             `json:"payload"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.JobID,
		arg.JobType,
		arg.Payload,
		arg.AvailableAt,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT job_id, job_type, payload, status, attempts, available_at,
       lease_owner, lease_until, created_at, updated_at
FROM guardian_jobs.jobs
WHERE job_id = $1
`

func (q *Queries) GetJob(ctx context.Context, jobID string) (GuardianJobsJob, error) {
	row := q.db.QueryRow(ctx, getJob, jobID)
	var i GuardianJobsJob
	err := row.Scan(
		&i.JobID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceState = `-- name: GetServiceState :one
SELECT state_key, state_value, updated_at
FROM guardian_system.service_state
WHERE state_key = $1
`

func (q *Queries) GetServiceState(ctx context.Context, stateKey string) (GuardianSystemServiceState, error) {
	row := q.db.QueryRow(ctx, getServiceState, stateKey)
	var i GuardianSystemServiceState
	err := row.Scan(&i.StateKey, &i.StateValue, &i.UpdatedAt)
	return i, err
}

const putServiceState = `-- name: PutServiceState :exec
INSERT INTO guardian_system.service_state (state_key, state_value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (state_key) DO UPDATE
SET state_value = EXCLUDED.state_value,
    updated_at = EXCLUDED.updated_at
`

type PutServiceStateParams struct {
	StateKey   string `json:"state_key"`
	StateValue []byte `json:"state_value"`
}

func (q *Queries) PutServiceState(ctx context.Context, arg PutServiceStateParams) error {
	_, err := q.db.Exec(ctx, putServiceState, arg.StateKey, arg.StateValue)
	return err
}
