// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GuardianAuditRecord struct {
	Sequence       int64              `json:"sequence"`
	EventID        pgtype.UUID        `json:"event_id"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	ActorType      string             `json:"actor_type"`
	ActorID        string             `json:"actor_id"`
	Action         string             `json:"action"`
	ObjectType     string             `json:"object_type"`
	ObjectID       string             `json:"object_id"`
	CorrelationID  string             `json:"correlation_id"`
	RequestID      pgtype.Text        `json:"request_id"`
	BeforeSnapshot []byte             `json:"before_snapshot"`
	AfterSnapshot  []byte             `json:"after_snapshot"`
}

type GuardianAuthAuthenticationThrottle struct {
	ScopeHash       []byte             `json:"scope_hash"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	Failures        int32              `json:"failures"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type GuardianAuthBootstrapToken struct {
	TokenID    pgtype.UUID        `json:"token_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GuardianAuthRecoveryCode struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CodeHash   []byte             `json:"code_hash"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GuardianAuthSession struct {
	SessionID        pgtype.UUID        `json:"session_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	TokenHash        []byte             `json:"token_hash"`
	CsrfHash         []byte             `json:"csrf_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	RevocationReason pgtype.Text        `json:"revocation_reason"`
}

type GuardianAuthUser struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Username         string             `json:"username"`
	Role             string             `json:"role"`
	Status           string             `json:"status"`
	PasswordPhc      string             `json:"password_phc"`
	TotpSeedEnvelope []byte             `json:"totp_seed_envelope"`
	LastTotpCounter  int64              `json:"last_totp_counter"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type GuardianDevicesCertificate struct {
	Serial            string             `json:"serial"`
	DeviceID          pgtype.UUID        `json:"device_id"`
	FingerprintSha256 string             `json:"fingerprint_sha256"`
	CertificatePem    []byte             `json:"certificate_pem"`
	NotBefore         pgtype.Timestamptz `json:"not_before"`
	NotAfter          pgtype.Timestamptz `json:"not_after"`
	State             string             `json:"state"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type GuardianDevicesCertificateAuthority struct {
	Singleton          bool               `json:"singleton"`
	CertificatePem     []byte             `json:"certificate_pem"`
	PrivateKeyEnvelope []byte             `json:"private_key_envelope"`
	NotAfter           pgtype.Timestamptz `json:"not_after"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type GuardianDevicesDevice struct {
	DeviceID      pgtype.UUID        `json:"device_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	DisplayName   string             `json:"display_name"`
	State         string             `json:"state"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GuardianDevicesEnrollmentThrottle struct {
	ScopeHash       []byte             `json:"scope_hash"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	Failures        int32              `json:"failures"`
	BlockedUntil    pgtype.Timestamptz `json:"blocked_until"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type GuardianDevicesEnrollmentToken struct {
	TokenID    pgtype.UUID        `json:"token_id"`
	DeviceID   pgtype.UUID        `json:"device_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GuardianJobsJob struct {
	JobID       string             `json:"job_id"`
	JobType     string             `json:"job_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
	LeaseOwner  pgtype.Text        `json:"lease_owner"`
	LeaseUntil  pgtype.Timestamptz `json:"lease_until"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GuardianSystemServiceState struct {
	StateKey   string             `json:"state_key"`
	StateValue []byte             `json:"state_value"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
