// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	AppendAuditRecord(ctx context.Context, arg AppendAuditRecordParams) (AppendAuditRecordRow, error)
	CreateJob(ctx context.Context, arg CreateJobParams) error
	GetJob(ctx context.Context, jobID string) (GuardianJobsJob, error)
	GetServiceState(ctx context.Context, stateKey string) (GuardianSystemServiceState, error)
	PutServiceState(ctx context.Context, arg PutServiceStateParams) error
}

var _ Querier = (*Queries)(nil)
